### ISSUE TITLE
GT4 available?

### ISSUE THREAD

**Issue by geppo1988** [assetto-corsa-web/accweb#81]
Hi! When are GT4 coming into ACCWEB? :)

Let me know if you need help

Thanks

**Comment by Kugelschieber** [comment]
I don't know yet, but this should be easy as it only requires adding the new tracks/cars to the options. You can try that if you like.

**Comment by geppo1988** [comment]
DO you know which config files are affected? I think they introduced some category ... I haveto see on their documentation

**Comment by Kugelschieber** [comment]
Okay that's a different case then. I haven't looked at the changes.

**Comment by mikeev261** [comment]
It seems like a minor change. They added a new field in settings.json: 

	"carGroup": "FreeForAll",

FreeForAll is the default, which is essentially just open mixed-class racing. 

From the V8 doc: 

Defines the car group for this server. Possible values are
"FreeForAll", "GT3", "GT4", "Cup", "ST"
where “FreeForAll” will allow any driver to join with any car
(that he defined as Primary Car).
GT3, GT4, Cup, ST will restrict this server to GT3, GT4,
Porsche Cup oder Lamborghini Supertrofeo.

**Comment by geppo1988** [comment]
So we need just to add this as an option in the ACCWEB when a new lobby is configured....is it a bbig change? I'm a developer but I'm not familiar with your project structure....

Maybe you can tell me which are the files and I'll change them :)

**Comment by Kugelschieber** [comment]
You can add that field to the server structure here: https://github.com/assetto-corsa-web/accweb/blob/master/server/server.go
And to the configuration in the frontend in the components over here: https://github.com/assetto-corsa-web/accweb/tree/master/public/src/components/server_config

**Comment by geppo1988** [comment]
Thanks :) How can I compile it once I changed the configs?

**Comment by Kugelschieber** [comment]
Oh I should have probably added that to the readme. Well you need to have npm (NodeJs) and Go (golang.org) installed. You can then cd into the public directory, run `npm i` to install all dependencies and `npm run build` to build the frontend. Afterwards you can start accweb in dev mode by running `go run main.go` in the root directory.

**Comment by geppo1988** [comment]
Hi,

Thanks for the help so far.

 changed settings,vue and server.go adding the enxtra field in the json and in the UI but I'm still struggling to get it working. Is there any other step I have to do to get it running locally?

**Comment by Kugelschieber** [comment]
Hm what error message do you see?

**Comment by geppo1988** [comment]
I see the parameter on the UI a bit messed up...probably I'm using "npm run" in the wrong way. Should I pass any parameters there?

**Comment by Kugelschieber** [comment]
Theoretically yes, you should also check they are loaded in the frontend again.

**Comment by geppo1988** [comment]
Yes everything works :) I'll do a final test on my server to see if the lobbies are created correctly :)

I have other features in mind...let's see

**Comment by mikeev261** [comment]
Looking forward to it. Thanks for making the change, @geppo1988 !

**Comment by geppo1988** [comment]
Hi, I'm finally building using the build script in the source but It's stopping cause he couldn't find the main and main.exe file.

Do you have an idea on how to fix it?

**Comment by geppo1988** [comment]
Maybe is better if I wait cause locally the generated json is ok but on the newely built release the property does not get filled in settings.json....

**Comment by Kugelschieber** [comment]
Sounds like you haven't updated the game.

**Comment by Kugelschieber** [comment]
Can you create a pull request so I can take a look at the changes?

**Comment by geppo1988** [comment]
ok course, I'll do itsoon

**Comment by geppo1988** [comment]
I created the pull request :) let me know if you think the changes are fine....probably I struggle just in the building process.....

**Comment by geppo1988** [comment]
Let me know if it bbuilds and works on your side so that we can release the 1.9.3 :) with suport of GT4

**Comment by KingWilly1** [comment]
I have download the new version 1.10.0 still the same problem. 

22338: ==ERR: Server is outdated and can't connect to the lobby anymore. Please update this server

**Comment by Kugelschieber** [comment]
Did the config version change?

**Comment by Kugelschieber** [comment]
This sounds more like an issue with the server version itself, not accweb.

**Comment by KingWilly1** [comment]
Did you change the exe file ?

**Comment by Kugelschieber** [comment]
What do you mean? You need to provide the accServer exe yourself, I cannot do that. Please check it's up to date.

**Comment by KingWilly1** [comment]
accweb release 1.10.0 is working. 

I have updated the exe file, after that the server is up and running. 

Thanks for the support guys.

**Comment by Kugelschieber** [comment]
@geppo1988 close this if it works for you.

**Comment by geppo1988** [comment]
ahhhhh maybe that was the issue on m side as well :) I fortgot to updte the accserver....

**Comment by AKM-Andy** [comment]
Hi Guys this is in changelog....
- Server: added "isLockedPrepPhase" setting (settings.json) to prevent clients who did not take part in qualifying from joining during the preparation/countdown phase.
Has it been overlooked?

**Comment by wakcs** [comment]
Small note, this fix in fact broke GT3 only servers 😅 https://github.com/assetto-corsa-web/accweb/commit/21cfc76ff79745d2409c3d3ac1f8d5dff64e78ef

**Comment by mikeev261** [comment]
Can confirm. GT3-only is in-fact broken. 

Interestingly, GT4-only works fine. Same with FreeForAll of course. Haven't tested CUP and ST yet.

**Comment by geppo1988** [comment]
I fixed already the code for GT3 :) sorry but it was a typo in the code. New release will come soon.

What about isLockedPrepPhase? is there or is just missing in the UI? I'll check if I can add this as well

**Comment by geppo1988** [comment]
@AKM-Andy https://www.assettocorsa.net/forum/index.php?threads/the-server-admin-handbook-thread.58245/
if you read in kunos documentation this parameter is not there :/ where have you find it?

**Comment by luismercury** [comment]
Hi.
There is a error
![image](https://user-images.githubusercontent.com/48275749/87815185-8d737080-c83b-11ea-8c30-0ee1a6315124.png)

Is correct "cargroup" GT3_2018 ??

**Comment by Kugelschieber** [comment]
Should be solved in 1.10.1.

**Comment by AKM-Andy** [comment]
> @AKM-Andy https://www.assettocorsa.net/forum/index.php?threads/the-server-admin-handbook-thread.58245/
> if you read in kunos documentation this parameter is not there :/ where have you find it?

I found it in Changelog within ACC

**Comment by AKM-Andy** [comment]
Hi Guys is everyone getting correct version number at bottom of server list as its still showing v1.10.0 on mine & I'm sure its updated???

**Comment by Kugelschieber** [comment]
Ah yes, I forgot to update that.

**Comment by AKM-Andy** [comment]
Has "isLockedPrepPhase" been added?

**Comment by Kugelschieber** [comment]
No, @geppo1988 just fixed the car groups.

**Comment by AKM-Andy** [comment]
Hi Guys, I have had to add it manually as its needed to stop GT3 cars being behind GT4 on grid because they didn't qualify or joined session late. GT3 cars ploughing through the field at start causes mayhem
